COLUMN NOM FORMAT A20;
COLUMN PRENOM FORMAT A20;     
COLUMN EMAIL FORMAT A30;
COLUMN NUMERO FORMAT A10;
COLUMN CODEPOSTAL FORMAT A6;
COLUMN VILLE FORMAT A20;
COLUMN DATENAISSANCE FORMAT A10;
COLUMN PARTIEENCOURS FORMAT A5;

COLUMN IDTYPEBATEAU FORMAT A2;
COLUMN TAILLE FORMAT A2;

COLUMN IDBATEAU FORMAT A3;
COLUMN IDPARTIE FORMAT A3;

SET pagesize 5000;
SET lines 400;